version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: gunicorn Coursecompass.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../:/app
    ports:
      - "80:8000"
    env_file:
      - docker/.env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password

volumes:
  postgres_data:
