version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: gunicorn your_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../:/app
    ports:
      - "80:8000"
    env_file:
      - docker/.env

